/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fuse_rpc.h"


void
compute_6(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	getattr_ret result_1;
	getattr_arg  bb_getattr_6_arg;
	enum clnt_stat retval_2;
	access_ret result_2;
	access_arg  bb_access_6_arg;
	enum clnt_stat retval_3;
	mkdir_ret result_3;
	mkdir_arg  bb_mkdir_6_arg;
	enum clnt_stat retval_4;
	rmdir_ret result_4;
	rmdir_arg  bb_rmdir_6_arg;
	enum clnt_stat retval_5;
	opendir_ret result_5;
	opendir_arg  bb_opendir_6_arg;
	enum clnt_stat retval_6;
	readdir_ret result_6;
	readdir_arg  bb_readdir_6_arg;
	enum clnt_stat retval_7;
	releasedir_ret result_7;
	releasedir_arg  bb_releasedir_6_arg;
	enum clnt_stat retval_8;
	rename_ret result_8;
	rename_arg  bb_rename_6_arg;
	enum clnt_stat retval_9;
	symlink_ret result_9;
	symlink_arg  bb_symlink_6_arg;
	enum clnt_stat retval_10;
	readlink_ret result_10;
	readlink_arg  bb_readlink_6_arg;
	enum clnt_stat retval_11;
	mknod_ret result_11;
	mknod_arg  bb_mknod_6_arg;
	enum clnt_stat retval_12;
	truncate_ret result_12;
	truncate_arg  bb_truncate_6_arg;
	enum clnt_stat retval_13;
	unlink_ret result_13;
	unlink_arg  bb_unlink_6_arg;
	enum clnt_stat retval_14;
	utime_ret result_14;
	utime_arg  bb_utime_6_arg;
	enum clnt_stat retval_15;
	chmod_ret result_15;
	chmod_arg  bb_chmod_6_arg;
	enum clnt_stat retval_16;
	chown_ret result_16;
	chown_arg  bb_chown_6_arg;
	enum clnt_stat retval_17;
	open_ret result_17;
	open_arg  bb_open_6_arg;
	enum clnt_stat retval_18;
	release_ret result_18;
	release_arg  bb_release_6_arg;
	enum clnt_stat retval_19;
	read_ret result_19;
	read_arg  bb_read_6_arg;
	enum clnt_stat retval_20;
	write_ret result_20;
	write_arg  bb_write_6_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, COMPUTE, COMPUTE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = bb_getattr_6(&bb_getattr_6_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = bb_access_6(&bb_access_6_arg, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = bb_mkdir_6(&bb_mkdir_6_arg, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = bb_rmdir_6(&bb_rmdir_6_arg, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = bb_opendir_6(&bb_opendir_6_arg, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = bb_readdir_6(&bb_readdir_6_arg, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_7 = bb_releasedir_6(&bb_releasedir_6_arg, &result_7, clnt);
	if (retval_7 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_8 = bb_rename_6(&bb_rename_6_arg, &result_8, clnt);
	if (retval_8 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_9 = bb_symlink_6(&bb_symlink_6_arg, &result_9, clnt);
	if (retval_9 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_10 = bb_readlink_6(&bb_readlink_6_arg, &result_10, clnt);
	if (retval_10 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_11 = bb_mknod_6(&bb_mknod_6_arg, &result_11, clnt);
	if (retval_11 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_12 = bb_truncate_6(&bb_truncate_6_arg, &result_12, clnt);
	if (retval_12 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_13 = bb_unlink_6(&bb_unlink_6_arg, &result_13, clnt);
	if (retval_13 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_14 = bb_utime_6(&bb_utime_6_arg, &result_14, clnt);
	if (retval_14 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_15 = bb_chmod_6(&bb_chmod_6_arg, &result_15, clnt);
	if (retval_15 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_16 = bb_chown_6(&bb_chown_6_arg, &result_16, clnt);
	if (retval_16 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_17 = bb_open_6(&bb_open_6_arg, &result_17, clnt);
	if (retval_17 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_18 = bb_release_6(&bb_release_6_arg, &result_18, clnt);
	if (retval_18 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_19 = bb_read_6(&bb_read_6_arg, &result_19, clnt);
	if (retval_19 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_20 = bb_write_6(&bb_write_6_arg, &result_20, clnt);
	if (retval_20 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	compute_6 (host);
exit (0);
}
